version: "3.7"
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/todo-lists
#    links:
#    - db
  db:
    image: mongo
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./db-volume:/data/db
