version: "3.7"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/todo-lists
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb
  mongodb:
    image: mongo
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./db-volume:/data/db
